language: python
python:
  #- "3.2"
  - 2.7

install:
  - pip install . --use-mirrors
  - pip install coveralls --use-mirrors

script:
  - nosetests --with-coverage --cover-package=srcds

after_success:
  - coveralls
