language: python
python:
  - "3.2"
  - "2.7"
  - "2.6"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install pylint --use-mirrors"
# command to run tests
script: pylint
